services:
  - type: web
    name: women-safety-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python website/manage.py collectstatic --noinput
      python website/manage.py migrate
    startCommand: gunicorn website.wsgi:application